"""Public exports for the Automation Bridge Python wrapper."""

from .client import (
    PYTHON_PACKAGE_VERSION,
    SUPPORTED_API_VERSION_MAX,
    SUPPORTED_API_VERSION_MIN,
    AutomationBridgeApiError,
    AutomationBridgeClient,
    AutomationBridgeError,
    EngineLogStream,
    HttpError,
    IncompatibleApiVersionError,
    InputController,
    InputExecutionError,
    InputInterruptionScope,
    InputReceipt,
    PointerSession,
    SelectorError,
    UnsupportedCapabilityError,
)
from .editor import EditorClient
from .lifecycle import FinalizationHooks
from .gestures import GestureConstraintError, GestureGenerator, generate_drag
from .nodes import Bounds, Node
from .events import CommandTimeout, Event, EventBufferOverflow, EventStream, StateSnapshot
from .profiler import ProfilerClient, ProfilerDataError, ResourceProfileEntry, parse_resources_data
from .receipts import ObservationReceipt, ScreenshotReceipt
from .visual import VisualClient, VisualObservation, difference
from .remotery import (
    RemoteryCapture,
    RemoteryClient,
    RemoteryCounterStats,
    RemoteryError,
    RemoteryFrame,
    RemoteryProtocolError,
    RemoteryProperty,
    RemoteryPropertyEntry,
    RemoteryPropertyFrame,
    RemoteryRecording,
    RemoterySample,
    RemoterySampleAggregate,
    RemoteryScopeStats,
    RemoteryTimingStats,
    RemoteryTimeoutError,
    RemoteryValueStats,
)
from .waits import WaitTimeoutError, wait_until
from .recording import (
    FFmpegRecordingBackend,
    RecordingCapabilities,
    RecordingError,
    RecordingMetadata,
    RecordingOptions,
    RecordingSession,
    UnsupportedRecordingCapability,
)
from .trace import REPLAY_PREREQUISITES, TRACE_VERSION, TraceError, TraceSession


__all__ = [
    "PYTHON_PACKAGE_VERSION",
    "SUPPORTED_API_VERSION_MAX",
    "SUPPORTED_API_VERSION_MIN",
    "AutomationBridgeApiError",
    "AutomationBridgeClient",
    "Bounds",
    "AutomationBridgeError",
    "EngineLogStream",
    "CommandTimeout",
    "Event",
    "EventBufferOverflow",
    "EventStream",
    "EditorClient",
    "FinalizationHooks",
    "FFmpegRecordingBackend",
    "GestureConstraintError",
    "GestureGenerator",
    "HttpError",
    "IncompatibleApiVersionError",
    "InputController",
    "InputExecutionError",
    "InputInterruptionScope",
    "InputReceipt",
    "Node",
    "ObservationReceipt",
    "ProfilerClient",
    "ProfilerDataError",
    "PointerSession",
    "RecordingCapabilities",
    "RecordingError",
    "RecordingMetadata",
    "RecordingOptions",
    "RecordingSession",
    "RemoteryCapture",
    "RemoteryClient",
    "RemoteryCounterStats",
    "RemoteryError",
    "RemoteryFrame",
    "RemoteryProtocolError",
    "RemoteryProperty",
    "RemoteryPropertyEntry",
    "RemoteryPropertyFrame",
    "RemoteryRecording",
    "RemoterySample",
    "RemoterySampleAggregate",
    "RemoteryScopeStats",
    "RemoteryTimingStats",
    "RemoteryTimeoutError",
    "RemoteryValueStats",
    "ResourceProfileEntry",
    "SelectorError",
    "StateSnapshot",
    "ScreenshotReceipt",
    "VisualClient",
    "VisualObservation",
    "difference",
    "WaitTimeoutError",
    "TRACE_VERSION",
    "TraceError",
    "TraceSession",
    "REPLAY_PREREQUISITES",
    "UnsupportedRecordingCapability",
    "generate_drag",
    "UnsupportedCapabilityError",
    "parse_resources_data",
    "wait_until",
]
